### ISSUE TITLE
Gamepad support

### ISSUE THREAD

**Issue by drsounds** [selgesel/godot4-third-person-controller#2]
Is there support for gamepads like Xbox controllers?

**Comment by selgesel** [comment]
I know this is a super late reply but better late then never, I guess.

Though no joypad buttons are assigned to any actions in the example code, all input event handling rely on actions, and the movement direction is determined by `Input.get_action_strength` and/or `Input.get_vector` so all controllers recognized by Godot should just work.

I don't have a controller so I can't verify it, nor assign some defaults, but please feel free to reopen this issue if you notice any issues with controllers.

Edit: Whoops, just realized panning wouldn't work as-is. Please see the PR #5 for this feature.
